name: Base images build

on:
  schedule:
  - cron: '0 3 * * *' # 3 AM UTC = before the nightly build
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    if: ${{ github.repository == 'shipwright-io/build' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin quay.io

      - name: Build Git
        run: |
          pushd images/git
            IMAGE=quay.io/shipwright/base-git docker buildx bake --push -f ../docker-bake.hcl
          popd
