name: Nightly Release

on:
  workflow_dispatch:  # Manual trigger

  schedule:
  - cron: '0 5 * * *' # 5 AM UTC = Midnight EST

jobs:
  nightly:
    if: ${{ github.repository == 'shipwright-io/build' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%s')"

    - name: Install Go
      uses: actions/setup-go@v2
    - name: Install Ko
      uses: imjasonh/setup-ko@20b7695b536c640edfafdd378d96c760460f29d6

    - name: Generate and upload release YAMLs
      env:
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        IMAGE_HOST: quay.io
        IMAGE: shipwright/shipwright-operator
        TAG: "nightly-${{ steps.date.outputs.date }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make release

        mv release.yaml nightly-${{ steps.date.outputs.date }}.yaml
        gh release upload nightly nightly-${{ steps.date.outputs.date }}.yaml

        mv release-debug.yaml nightly-${{ steps.date.outputs.date }}-debug.yaml
        gh release upload nightly nightly-${{ steps.date.outputs.date }}-debug.yaml
