---
name: Sanity Checks

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Sanity Checks
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install Tools
      run: |
        pushd $(mktemp -d)
        go get github.com/gordonklaus/ineffassign
        go get golang.org/x/lint/golint
        go get github.com/client9/misspell/cmd/misspell
        go get honnef.co/go/tools/cmd/staticcheck
        popd

    - name: Sanity Check (go vet)
      run: make govet

    - name: Sanity Check (ineffassign)
      run: make ineffassign

    - name: Sanity Check (golint)
      run: make golint

    - name: Sanity Check (misspell)
      run: make misspell

    - name: Sanity Check (staticcheck)
      run: make staticcheck
